In [1]:
!pwd

/home/keng/cs224n/assignment1


In [2]:
from q1_softmax import softmax, test_softmax_basic, test_softmax
from q2_sigmoid import sigmoid, sigmoid_grad, test_sigmoid_basic, test_sigmoid
import q2_gradcheck
import q2_neural 
from q3_word2vec import test_normalize_rows, test_word2vec
import q3_sgd 

from pprint import pprint

import numpy as np

%load_ext autoreload
%autoreload 2

In [3]:
# q1 Test Softmax
test_softmax_basic()
test_softmax()

Running basic tests...
[0.26894142 0.73105858]
[[0.26894142 0.73105858]
 [0.26894142 0.73105858]]
[[0.73105858 0.26894142]]
You should be able to verify these results by hand!

Running your tests...
[5.62554730e-04 1.52918230e-03 1.52918230e-03 1.12992138e-02
 3.07144476e-02 8.34905247e-02 2.26950776e-01 6.16916170e-01
 2.52772134e-04 1.12992138e-02 4.15674846e-03 1.12992138e-02]
[[2.68941421e-01 7.31058579e-01]
 [5.64636292e-01 4.35363708e-01]
 [7.31058579e-01 2.68941421e-01]
 [4.71116580e-58 1.00000000e+00]
 [0.00000000e+00 1.00000000e+00]
 [7.58256042e-10 9.99999999e-01]
 [9.99999998e-01 2.06115362e-09]
 [4.53978687e-05 9.99954602e-01]]
[[7.31058579e-01 2.68941421e-01 1.00048252e-44 3.68056951e-45]]


In [4]:
# q2 Test Sigmoid and Grad
test_sigmoid_basic();
test_sigmoid()


Running basic tests...
[[0.73105858 0.88079708]
 [0.26894142 0.11920292]]
[[0.19661193 0.10499359]
 [0.19661193 0.10499359]]
You should verify these results by hand!

Running your tests...
[[0.73105858 0.88079708]
 [0.26894142 0.11920292]
 [0.73105858 0.88079708]
 [0.26894142 0.11920292]]
[[0.19661193 0.10499359]
 [0.19661193 0.10499359]
 [0.19661193 0.10499359]
 [0.19661193 0.10499359]]


In [5]:
q2_gradcheck.sanity_check()
q2_gradcheck.your_sanity_checks()

Running sanity checks...
Gradient check passed!
Gradient check passed!
Gradient check passed!

Running your sanity checks...
Gradient check passed!
Gradient check passed!
Gradient check passed!


In [6]:
q2_neural.sanity_check()
# q2_neural.your_sanity_checks()

Running sanity check...
Gradient check passed!


In [7]:
# Test sigmoid(-a) = 1 - sigmoid(a)
v = 10
pprint(sigmoid(v))
pprint(sigmoid(-v))
pprint(1.0 - sigmoid(v))


0.9999546021312976
4.5397868702434395e-05
4.5397868702390376e-05


In [8]:
v = np.array([2, 6, -2, -6])
pprint(v.shape)
pprint(v.T.shape)
pprint(sigmoid(v))
pprint(sigmoid(-v))
pprint(1.0 - sigmoid(v))


(4,)
(4,)
array([0.88079708, 0.99752738, 0.11920292, 0.00247262])
array([0.11920292, 0.00247262, 0.88079708, 0.99752738])
array([0.11920292, 0.00247262, 0.88079708, 0.99752738])


In [9]:
# q3_word2vec.py
test_normalize_rows()
test_word2vec()

Testing normalizeRows...
[[0.6        0.8       ]
 [0.4472136  0.89442719]]

==== Gradient check for skip-gram ====
Gradient check passed!
Gradient check passed!

==== Gradient check for CBOW      ====
Gradient check passed!
Gradient check passed!

=== Results ===
(11.16610900153398, array([[ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [-1.26947339, -1.36873189,  2.45158957],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ]]), array([[-0.41045956,  0.18834851,  1.43272264],
       [ 0.38202831, -0.17530219, -1.33348241],
       [ 0.07009355, -0.03216399, -0.24466386],
       [ 0.09472154, -0.04346509, -0.33062865],
       [-0.13638384,  0.06258276,  0.47605228]]))
(13.959405258751875, array([[ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [-4.12113804, -1.67347865, -1.5049951 ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.       

In [11]:
# q3_sgd.py
q3_sgd.sanity_check()
# q3_sgd.your_sanity_check()

Running sanity checks...
iter 100: 0.004578
iter 200: 0.004353
iter 300: 0.004136
iter 400: 0.003929
iter 500: 0.003733
iter 600: 0.003546
iter 700: 0.003369
iter 800: 0.003200
iter 900: 0.003040
iter 1000: 0.002888
test 1 result: 8.41483678608e-10
iter 100: 0.000000
iter 200: 0.000000
iter 300: 0.000000
iter 400: 0.000000
iter 500: 0.000000
iter 600: 0.000000
iter 700: 0.000000
iter 800: 0.000000
iter 900: 0.000000
iter 1000: 0.000000
test 2 result: 0.0
iter 100: 0.041205
iter 200: 0.039181
iter 300: 0.037222
iter 400: 0.035361
iter 500: 0.033593
iter 600: 0.031913
iter 700: 0.030318
iter 800: 0.028802
iter 900: 0.027362
iter 1000: 0.025994
test 3 result: -2.52445103582e-09

